### PR TITLE
Richtext fix

### PR DESCRIPTION
**Pull request by smcmahon**
Fix for issue #23; failure to index rich text fields in 4.3.14.

### CODE REVIEW

**Comment by smcmahon** [comment]
Tests do pass for plone 4.3.x. 5.x tests not currently working for this module.

**Comment by jensens** [comment]
Plone 5.0.7 has some problem left, with 5.0.6 all is fine

**Comment by gforcada** [comment]
I'm late at the party but I noticed that some file permissions where switched to 755, which I guess is not expected.

**Comment by jensens** [comment]
@gforcada I'll switch them back to 644

**Comment by jensens** [comment]
@gforcada I corrected them. Would this something for code-analysis to check?

**Comment by gforcada** [comment]
@jensens yes, could be, would you mind creating the issue on p.r.codeanalysis?

**Pull request merged**
